apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
  annotations:
    # Tell Image Updater which image to track
    argocd-image-updater.argoproj.io/image-list: |
      python-app=512897090915.dkr.ecr.us-east-1.amazonaws.com/python-app

    # Use immutable digests (recommended)
    argocd-image-updater.argoproj.io/python-app.update-strategy: digest

    # Where to write the image update
    argocd-image-updater.argoproj.io/write-back-method: git

    # Helm value to update
    argocd-image-updater.argoproj.io/python-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/python-app.helm.image-tag: image.tag

    # Commit message
    argocd-image-updater.argoproj.io/git-commit-message: |
      chore(image): update python-app image

spec:
  project: default

  source:
    repoURL: https://github.com/julio-ruiz-m/python-app
    targetRevision: main
    path: helm/python-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

 