apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      python-app=512897090915.dkr.ecr.us-east-1.amazonaws.com/python-app
    
    argocd-image-updater.argoproj.io/python-app.update-strategy: latest
    argocd-image-updater.argoproj.io/python-app.allow-tags: regexp:^[a-f0-9]{40}$
    argocd-image-updater.argoproj.io/python-app.force-update: "true"
    
    # THIS IS KEY - tells image-updater to use ECR authentication via IRSA
    argocd-image-updater.argoproj.io/python-app.platform: linux/amd64
    
    argocd-image-updater.argoproj.io/write-back-method: git
    
    argocd-image-updater.argoproj.io/python-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/python-app.helm.image-tag: image.tag
    
    argocd-image-updater.argoproj.io/git-commit-message: |
      chore(image): update python-app image


spec:
  project: default

  source:
    repoURL: https://github.com/julio-ruiz-m/python-app
    targetRevision: main
    path: helm/python-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
 