name: app-ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPO: python-app
  AWS_ACCOUNT_ID: 512897090915

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - run: pip install -r requirements.txt
      - run: pytest

  validate-gitops:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4


      - name: Helm lint
        run: |
          helm lint helm/python-app

      - name: Helm template render
        run: |
          helm template python-app helm/python-app \
            -f helm/python-app/values.yaml \
            > /tmp/rendered.yaml

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Validate Argo Application manifest
        run: |
          kubectl apply \
            --dry-run=client \
            -f argocd/application.yaml

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::512897090915:role/github-ecr-push
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

        
      - name: Build image
        run: |
          docker build \
            -t $ECR_REPO:latest \
            -t $ECR_REPO:${{ github.sha }} \
            .


      -  name: Scan image (local)
         uses: aquasecurity/trivy-action@0.20.0
         with:
           image-ref: python-app:${{ github.sha }}
           severity: CRITICAL,HIGH
           vuln-type: os,library
           exit-code: 1



      - name: Tag & push
        run: |
          for tag in latest ${{ github.sha }}; do
            docker tag $ECR_REPO:$tag \
              ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:$tag

            docker push \
              ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPO:$tag
          done